### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by ldcyx** [duguyue100/pyaer#1]
dongchen@dongchen-ThinkPad-T430s:~$ python2 test_dynapse.py 
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "test_dynapse.py", line 7, in <module>
    from pyaer.dynapse import DYNAPSE
  File "/home/dongchen/.local/lib/python2.7/site-packages/pyaer/__init__.py", line 22, in <module>
    raise ImportError("libcaer might not be in the LD_LIBRARY_PATH "
ImportError: libcaer might not be in the LD_LIBRARY_PATH or your numpy might not be the required version.Try to load _libcaer_wrap.so from the package directory, this will provide more information.

**Comment by duguyue100** [comment]
You need to update your numpy version because the pyaer is compiled against the latest numpy, try running `pip install numpy -U` to fix the problem.

**Comment by ldcyx** [comment]
Successfully installed numpy-1.11.0

**Comment by duguyue100** [comment]
the pyaer is compiled aganist 1.14.2
Can you further upgrade?

**Comment by ldcyx** [comment]
This is how it looks like. I tried 1.14.2, but it is still 1.11.0 installed. Maybe I need to update the pip? But updating pip has the same problem. 

dongchen@dongchen-ThinkPad-T430s:~$ pip install numpy==1.14.2
Collecting numpy==1.14.2
  Using cached https://files.pythonhosted.org/packages/76/4d/418dda252cf92bad00ab82d6b2a856e7843b47a5c2f084aed34b14b67d64/numpy-1.14.2-cp27-cp27mu-manylinux1_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.11.0
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by ldcyx** [comment]
It works now. Thanks!!

**Comment by shirleyatgithub** [comment]
numpy 1.14.2 is not compatible with python37. Do you have any suggestion?
