### ISSUE TITLE
Wrong special event data

### ISSUE THREAD

**Issue by jereroy** [duguyue100/pyaer#13]
Hi!

I had some problems with the _get_special_event_ function in device.py. The special event data returned was always 0 no matter what. The timestamp and the number of special event were fine.

I fixed it by modifying the _get_special_event_ in pyflags.i :  
```
%inline %{
void get_special_event(caerSpecialEventPacket event_packet, int64_t* event_vec, int32_t packet_len) {
    long i;
    for (i=0; i<(int)packet_len/2; i++) {
        caerSpecialEvent event = caerSpecialEventPacketGetEvent(event_packet, i);
        event_vec[i*2] = caerSpecialEventGetTimestamp(event);
        //event_vec[i*2+1] = caerSpecialEventGetData(event); <-- OLD ONE
        event_vec[i*2+1] =  U32T(le32toh(event->data) >> (SPECIAL_TYPE_SHIFT)) & (SPECIAL_TYPE_MASK); //<-- NEW ONE
    }
}
%}
```

However, I don't quite understand why it works.... The GET_NUMBITS32 function in the libcaer library always returns me 0.

Maybe it could cause other problems in the future?

**Comment by duguyue100** [comment]
Hi, I'm not exactly sure what's the reason too. Let me repost this issue to `libcaer`, and see if they know anything particular. Thanks!

**Comment by duguyue100** [comment]
@jereroy Hi, `libcaer`'s team has replied in the above-mentioned issue, I will update a patch in the next release.
