### ISSUE TITLE
Patch level 1 is required

### ISSUE THREAD

**Issue by pinky77mm** [duguyue100/pyaer#16]
When I do python, the error shows that:
CRITICAL: DAVIS ID-1: Device logic patch level insufficient. You have patch level 0; but patch level 1 is required. Please update by following the Flashy documentation at 'https://inivation.com/support/software/reflashing/'.
2019-10-30 17:45:16 (TZ+0000): CRITICAL: DAVIS ID-1: Failed to open device, no matching device could be found or opened.
Traceback (most recent call last):
  File "davis240_test.py", line 14, in <module>
    raise ValueError("The device is failed to open.")
ValueError: The device is failed to open.

Do you have any idea about this problem?

**Comment by duguyue100** [comment]
@pinky77mm Sorry for the late reply, I think the main problem is that I haven't been updating libcaer version so that pyaer can catch firmware update. I will do the update in the next few days.
