### ISSUE TITLE
Script examples bias path

### ISSUE THREAD

**Issue by sanfans** [duguyue100/pyaer#6]
Hi Yuhuang, i tried your library with a DAVIS240C using last version of libcAER (just wanted to try and see if it worked, i didn't want to change version) running the file in scripts/davis240_test.py, and it works besides a little problem with the bias file path. If i run the script from shell it doesn't find the bias parameters file, because you set the default search path for the json file as: 
> "./scripts/configs/davis240c_config.json"

but if you run it inside the script folder he can't find it. Changing to 
> "./configs/davis240c_config.json"

everything works without any change, so you can run the script directly. Eventually i would put in this function:

> def load_json(file_path):

something like this for the IOError:
```python
errorString = "Error when trying to load bias file, not found in the specified location"
print(errorString)
raise
```
So that we know there is a problem in the file location.

However, i don't know if you use spyder with Anaconda, but if you change the working directory directory to the  pyaer directory (the top level one), it gives the errors:
> ImportError: libcaer might not be in the LD_LIBRARY_PATH or your numpy might not be the required version.Try to load _libcaer_wrap.so from the package directory, this will provide more information.

It seems that when you do:
> from pyaer import libcaer

It has conflict between the local directory pyaer and the one you installed with pip, because he searches for libcaer in the local directory, maybe for some reasons it has higher priority. Just to tell you, maybe this can happen to others.

**Comment by duguyue100** [comment]
Hi, @sanfans thanks for your detailed debug.

the IO error is specifically designed this way for now and will be changed soon. I'm fully aware that I need to complete the error message at the package wide.

In terms of the search path, Python always searches the local path first, so if you run the script somehow from the `scripts` folder would resolve the problem.

`pyaer` soon will contain a copy of `libcaer` so the version conflicts will be solved.

I will close this issue for now.

Yuhuang.

**Comment by sanfans** [comment]
Sure, no problem.
I opened an issue, instead sending a mail, so everything is tracked amd
other people can see it ;)
Thanks for the info

Il mar 10 lug 2018, 11:57 Yuhuang Hu <notifications@github.com> ha scritto:
